name: Log Time Job
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  log_time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Run logging script
        run: |
          chmod +x log_time.sh
          ./log_time.sh
      
      - name: Count log updates
        run: |
          chmod +x counts.sh
          ./counts.sh
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add log.txt log_count.txt
          git commit -m "Update log files with new timestamp and count" || echo "No changes to commit"
          git push
